### PR TITLE
django 2.1 compliant

### PR DESCRIPTION
**Pull request by ghost**
few line to fix the import of "reverse" from "urls" + on_delete on foreignkey

### CODE REVIEW

**Comment by Gagaro** [comment]
Hi, thanks for the PR :+1: .

Could you also upgrade the travis conf and add a changelog line. Thanks.

**Comment by ghost** [comment]
I don't get that point 
> add a changelog line.

in CHANGE.rst ?

for example 

```
1.0.7 (not released yet)
~~~~~~~~~~~~~~~~~~~~~~~~
* Python 3.5+ and Django 2.1 Compliant
```

**Comment by Gagaro** [comment]
Yes exactly :smile: .

**Comment by ghost** [comment]
ok ;)

**Comment by Gagaro** [comment]
Oups sorry about the delay but I didn't get a notification for this commit. Thanks for the PR, I'll finish fixing up the test and release this.

**Comment by ghost** [comment]
I hope the tests ran well because I'm not sure everything is fine due to generic relationship to cover.

**Comment by Gagaro** [comment]
There was a few things to fix but it's all good now.

**Pull request merged**
